apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      initContainers:
        - name: wait-for-rabbit
          image: busybox
          command: ['sh', '-c', 'until nc -z rabbitmq 5672; do echo waiting for rabbitmq; sleep 2; done;']
      containers:
        - name: consumer
          image: consumer:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBITMQ_CONN
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RabbitMqHost


    
      #     volumeMounts:
      #       - name: log-volume
      #         mountPath: /app
      #     env:
      #       - name: RABBITMQ_HOST
      #         value: "rabbitmq"  # Should match the service name of your RabbitMQ deployment
      # volumes:
      #   - name: log-volume
      #     emptyDir: {}
