apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: consumer-scaledobject
spec:
  scaleTargetRef:
    name: consumer
  pollingInterval: 5          # Check RabbitMQ every 5 seconds
  cooldownPeriod: 30          # Wait 30 seconds before scaling down
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: rabbitmq
      metadata:
        queueName: order_queue         # Replace with your queue name
        queueLength: "5"            # Trigger scale-up if > 5 messages
        hostFromEnv: RABBITMQ_CONN  # KEDA gets RabbitMQ connection string from env
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
data:
  RabbitMqHost: YW1xcDovL2d1ZXN0Omd1ZXN0QHJhYmJpdG1xOjU2NzIv  # e.g., amqp://guest:guest@rabbitmq:5672/
