apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      name: app-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-service
  template:
    metadata:
      labels:
        app: app-service
    spec:
      containers:
        - name: app-service
          image: app-service:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 5000  # replace with your app port
            name: app-service
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "200m"

